title = "TheExampleBarn"
tags = ["physics"]
content_fmt = "markdown"

[[q_a]]
question = "question 1"
answer = "ans 1"
tags = ["algorithms", "complexity"]

[[q_a]]
question = "are multi-line ans supported"
answer = """of course ~

- you can try this
- by yourself
"""
tags = ["algorithms"]