title = "RuntimeExampleBarn"
tags = ["complexity"]
content_fmt = "markdown"
runtime = true

[[q_a]]
  question = "this is a runtime example"
  answer = "# runtime ans\n\n  - 1\n  "
  tags = ["algorithms", "complexity"]
  [q_a.runtime]
    cid = 1705923679008
    nid = 1705923679007
    guid = "cHuNXOn9hM"
