title = "RuntimeExampleBarn"  # Optional. If not provided, the file name is used as the deck name.
runtime = true

[[q_a]]
question = "question 1"
answer = "ans 1"
tags = ["algorithms", "complexity"]

[[q_a]]
question = "are multi-line ans supported"
answer = """of course,
you can try this
by yourself
"""