title = "RuntimeExampleBarn"
runtime = true
tags = ["complexity"]
content_fmt = "markdown"

[[q_a]]
  tags = ["algorithms", "complexity"]
  question = "this is a runtime example"
  answer = "# runtime ans\n\n  - 1\n  "
  [q_a.runtime]
    cid = 1719645923007
    nid = 1705923679007
    guid = "IlVdoT4qTQ"
